// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOjaTsgGzGkfjeN7BrWnBT5SLGhkhWTY',
    appId: '1:315781797492:web:03967d5863cc79a0e4a321',
    messagingSenderId: '315781797492',
    projectId: 'deliveus-app',
    authDomain: 'deliveus-app.firebaseapp.com',
    storageBucket: 'deliveus-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjYMBLmAhRta9RHvbH8kxs-UtrOGDfZw',
    appId: '1:315781797492:android:5a98353e6e760856e4a321',
    messagingSenderId: '315781797492',
    projectId: 'deliveus-app',
    storageBucket: 'deliveus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBosewSUJAN1EGQnEpcjzOLpPL7GwnFNY',
    appId: '1:315781797492:ios:cb956e9949500b3ce4a321',
    messagingSenderId: '315781797492',
    projectId: 'deliveus-app',
    storageBucket: 'deliveus-app.appspot.com',
    iosClientId:
        '315781797492-4d3nm5cotre53igv0v626t7o5d3c62i1.apps.googleusercontent.com',
    iosBundleId: 'com.deleveus.org.deleveus-app',
  );
}
